on:
  - push
  - workflow_dispatch

name: Change Files

jobs:
  changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch
        id: get_branch
        shell: bash
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}")
          echo "::set-output name=branch::$BRANCH"

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Diff
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMPARE_TO="origin/dev"
          BRANCH=${{ steps.get_branch.outputs.branch }}
          if [[ "$BRANCH" == "dev" || "$BRANCH" == "main" ]]; then
            COMPARE_TO="HEAD~1"
          fi

          echo "Comparing diff between $BRANCH:HEAD and $COMPARE_TO"
          git --no-pager diff --name-only HEAD $COMPARE_TO

      - name: New diff
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          BEFORE: ${{ github.event.push.before }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo $BEFORE
          
