on:
  - push
  - workflow_dispatch

name: Change Files

jobs:
  changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: New diff
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          BEFORE: ${{ github.event.push.before }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo $BEFORE
          
      - name: New diff 2
        shell: bash
        env:
          BEFORE: ${{ github.event.before }}
          AFTER: ${{ github.event.after }}
        run: |
          echo $AFTER
          echo $BEFORE
          echo "Comparing diff between $AFTER and $BEFORE"
          git --no-pager diff --name-only $AFTER $BEFORE
